// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqQt_v2PlRIvvTZnPVmzfRcWRRe8ZSQAo',
    appId: '1:1019080859686:web:23f240969d322054bcc6e7',
    messagingSenderId: '1019080859686',
    projectId: 'mad-project-dd125',
    authDomain: 'mad-project-dd125.firebaseapp.com',
    storageBucket: 'mad-project-dd125.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQQu2So6Bq-_eraoE_1Xg12YfCS7rFtvA',
    appId: '1:1019080859686:android:502e8fb15d7b6c0dbcc6e7',
    messagingSenderId: '1019080859686',
    projectId: 'mad-project-dd125',
    storageBucket: 'mad-project-dd125.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKGBFxv8KFDVWvOA2C-Jk0nGD7p_29TmY',
    appId: '1:1019080859686:ios:22cb4cd0685c2a32bcc6e7',
    messagingSenderId: '1019080859686',
    projectId: 'mad-project-dd125',
    storageBucket: 'mad-project-dd125.firebasestorage.app',
    iosBundleId: 'com.example.madProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKGBFxv8KFDVWvOA2C-Jk0nGD7p_29TmY',
    appId: '1:1019080859686:ios:22cb4cd0685c2a32bcc6e7',
    messagingSenderId: '1019080859686',
    projectId: 'mad-project-dd125',
    storageBucket: 'mad-project-dd125.firebasestorage.app',
    iosBundleId: 'com.example.madProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqQt_v2PlRIvvTZnPVmzfRcWRRe8ZSQAo',
    appId: '1:1019080859686:web:f8d82f08ba0fd9e2bcc6e7',
    messagingSenderId: '1019080859686',
    projectId: 'mad-project-dd125',
    authDomain: 'mad-project-dd125.firebaseapp.com',
    storageBucket: 'mad-project-dd125.firebasestorage.app',
  );

}